basePath: /
definitions:
  users.User:
    properties:
      created_at:
        type: string
      id:
        type: integer
      updated_at:
        type: string
      username:
        type: string
    type: object
  users.authRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  users.errorResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: AirFlow description part
  title: AirFlow
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Авторизация пользователя по username и паролю
      parameters:
      - description: Данные для входа
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/users.authRequest'
      produces:
      - application/json
      responses:
        "200":
          description: id, username и сообщение
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Ошибка валидации
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Неверные учётные данные
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Внутренняя ошибка
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Вход пользователя
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/users.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "201":
          description: Created
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/users.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/users.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/users.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/users.errorResponse'
      summary: Register
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: AirFlow
    type: apiKey
swagger: "2.0"
